name: 🐛 Bug Report
description: รายงานบั๊กที่พบใน es_extended
labels: ["bug"]
title: "Bug: "
body:
  - type: markdown
    attributes:
      value: |
        **โปรดกรอกข้อมูลด้านล่างให้ครบถ้วน เพื่อให้เราสามารถตรวจสอบได้เร็วขึ้น**
  - type: input
    id: description
    attributes:
      label: รายละเอียดของบั๊ก
      description: อธิบายปัญหาที่พบ
      placeholder: "อธิบายสภาพปัญหา…"
      required: true
  - type: input
    id: steps
    attributes:
      label: ขั้นตอนการทำให้เกิดบั๊ก
      placeholder: "1. ...  2. ...  3. ..."
      required: true
  - type: input
    id: expected
    attributes:
      label: คาดหวังให้ระบบทำอะไร
      placeholder: "สิ่งที่ควรเกิดขึ้น…"
      required: true
  - type: input
    id: actual
    attributes:
      label: สิ่งที่เกิดขึ้นจริง
      placeholder: "สิ่งที่เกิดขึ้นจริง…"
      required: true